-- PostgreSQL Extensions Initialization Script
-- This script is automatically run on database initialization
-- to enable commonly used extensions.

-- Core contrib extensions (require CREATE EXTENSION)
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS hstore;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS tablefunc;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS intarray;
CREATE EXTENSION IF NOT EXISTS isn;
CREATE EXTENSION IF NOT EXISTS cube;
CREATE EXTENSION IF NOT EXISTS earthdistance;
CREATE EXTENSION IF NOT EXISTS bloom;
CREATE EXTENSION IF NOT EXISTS btree_gin;
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS pg_buffercache;
CREATE EXTENSION IF NOT EXISTS pgrowlocks;
CREATE EXTENSION IF NOT EXISTS pgstattuple;
CREATE EXTENSION IF NOT EXISTS pg_visibility;
CREATE EXTENSION IF NOT EXISTS pageinspect;
CREATE EXTENSION IF NOT EXISTS postgres_fdw;
CREATE EXTENSION IF NOT EXISTS file_fdw;
CREATE EXTENSION IF NOT EXISTS dblink;
CREATE EXTENSION IF NOT EXISTS dict_int;
CREATE EXTENSION IF NOT EXISTS dict_xsyn;
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS tsm_system_rows;
CREATE EXTENSION IF NOT EXISTS tsm_system_time;
CREATE EXTENSION IF NOT EXISTS xml2;
CREATE EXTENSION IF NOT EXISTS sslinfo;
CREATE EXTENSION IF NOT EXISTS lo;
CREATE EXTENSION IF NOT EXISTS old_snapshot;
CREATE EXTENSION IF NOT EXISTS seg;
CREATE EXTENSION IF NOT EXISTS ltree;
CREATE EXTENSION IF NOT EXISTS adminpack;

-- Scheduling extension (requires shared_preload_libraries)
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- Auditing extensions
CREATE EXTENSION IF NOT EXISTS pgaudit;
CREATE EXTENSION IF NOT EXISTS credcheck;

-- Performance and monitoring extensions
CREATE EXTENSION IF NOT EXISTS pg_stat_kcache;
CREATE EXTENSION IF NOT EXISTS pg_qualstats;
CREATE EXTENSION IF NOT EXISTS pg_wait_sampling;
CREATE EXTENSION IF NOT EXISTS hypopg;

-- Vector/AI extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Geospatial extensions
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_topology;
CREATE EXTENSION IF NOT EXISTS postgis_raster;
CREATE EXTENSION IF NOT EXISTS pgrouting;
CREATE EXTENSION IF NOT EXISTS h3;

-- Data types and utilities
CREATE EXTENSION IF NOT EXISTS hll;
CREATE EXTENSION IF NOT EXISTS ip4r;
CREATE EXTENSION IF NOT EXISTS prefix;
CREATE EXTENSION IF NOT EXISTS semver;
CREATE EXTENSION IF NOT EXISTS unit;
CREATE EXTENSION IF NOT EXISTS pgmp;
CREATE EXTENSION IF NOT EXISTS asn1oid;
CREATE EXTENSION IF NOT EXISTS debversion;

-- Foreign data wrappers
CREATE EXTENSION IF NOT EXISTS mysql_fdw;
CREATE EXTENSION IF NOT EXISTS ogr_fdw;
CREATE EXTENSION IF NOT EXISTS redis_fdw;

-- Partitioning and maintenance
CREATE EXTENSION IF NOT EXISTS pg_partman;
CREATE EXTENSION IF NOT EXISTS pg_repack;

-- Full-text search enhancements
CREATE EXTENSION IF NOT EXISTS rum;

-- Procedural language checks
CREATE EXTENSION IF NOT EXISTS plpgsql_check;

-- Replication and CDC
CREATE EXTENSION IF NOT EXISTS wal2json;
CREATE EXTENSION IF NOT EXISTS pglogical;

-- Utilities
CREATE EXTENSION IF NOT EXISTS http;
CREATE EXTENSION IF NOT EXISTS pgtap;
CREATE EXTENSION IF NOT EXISTS dirtyread;
CREATE EXTENSION IF NOT EXISTS extra_window_functions;
CREATE EXTENSION IF NOT EXISTS first_last_agg;
CREATE EXTENSION IF NOT EXISTS tablelog;
CREATE EXTENSION IF NOT EXISTS toastinfo;
CREATE EXTENSION IF NOT EXISTS prioritize;
CREATE EXTENSION IF NOT EXISTS show_plans;
